(* Chooser:                                         HDO, 2004-02-06
   -------
   Chooser for language features/extensions: Mini -> Midi
===================================================================*)


(*Comments: Definition of symbol 'Comments' enables Pascal-like
  --------  comments, used in MP_Lex only*)

(*$DEFINE Comments*)
{ (*$UNDEF Comments*) }


(*Midi: Definition of symbol 'Midi' enables IF/ELSE and WHILE statements
  ----  in the MiniPascal compiler only*)

(*$DEFINE Midi*)
{ (*$UNDEF Midi*) }
